src/Graucho/MoviesBundle/Form/KoszykType.php
<?php

namespace Graucho\MoviesBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class KoszykType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('tytul', 'text', array('label' => 'Tytuł filmu'))
            ->add('tresc', 'textarea', array('label' => 'Cena nabycia'))
            ->add('dataUtworzenia', 'date', array(
                'label' => 'Data zamówienia', 
                'widget' => 'single_text',
                'data' => new \DateTime("now")
                ))
            ->add('movie', 'entity', array(
                'class' => 'GrauchoMoviesBundle:Movie',
                'property' => 'tytul',
                'label' => 'Wybierz film do nabycia',
                ))
            ->add('save', 'submit', array(
                'label' => 'Prześlij zamówienie', 
                'attr' => array(
                    'class' => 'btn btn-primary'
                )
            ))
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Graucho\MoviesBundle\Entity\Koszyk'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'graucho_moviesbundle_koszyk';
    }
}

src/Graucho/MoviesBundle/Resources/views/Movies/c.html.twig
{% extends "GrauchoMoviesBundle::bars.html.twig" %}

{% block header %}
	Filmy {{cat}}
{% endblock %}

{% block content %}
		
	<!-- movies list from db. by gerne-->
	<table class="table">
	{% set items = movies %}
	{% for row in movies|batch(3) %}
		<tr>
			{% for column in row %}
				<td>
				{% set img = 'bundles/grauchomovies/images/' ~ column.img %}
				{% set id = column.id %}
				<a href="{{path('graucho_movies_movie', {'id': id})}}">{{ column.name }}</a><br>
				<a href="{{path('graucho_movies_movie', {'id': id})}}"><img class="img-thumbnail" src={{ asset(img)}}></a> 
				</td>
			{% endfor %}
		</tr>
	{% endfor %}
	</table>

{% endblock %}

src/Graucho/MoviesBundle/Resources/views/Movies/movie.html.twig
{% extends "GrauchoMoviesBundle::bars.html.twig" %}

{% block header %}
	{{movie[0].name}}
{% endblock %}

{% block content %}
	
	{% set img = 'bundles/grauchomovies/images/' ~ movie[0].img %}

<div class="container">
	<div class="page-header"><h2 style="display: inline-block;">{{movie[0].name}} </h2><span>     ({{movie[0].data|date('Y-m-d')}})</span>
	</div>
	<div class="col-md-4">
		<div class="row">
			<img class="img-thumbnail" src={{ asset(img)}}>
		</div>
		<div class="page-header" >	
			Aktorzy:<br> {{movie[0].aktorzy}}<br>
			Cena:    {{movie[0].value}} PLN
		</div>
	</div>
	<div class="col-md-8">
		<div class="row">
			<p>{{movie[0].opis}}</p>
		</div>
	</div>
</div>
<div class="col-md-12" style="margin-bottom:20px;">
		<a href="{{path('graucho_movies_koszyk_add', {'id': movie[0].id})}}" class="btn btn-primary">Do koszyka</a>
		{% if is_granted('ROLE_USER') %}
			<a href="{{path('graucho_movies_recenzja_add', {'id': movie[0].id})}}" class="btn btn-primary">Recenzuj</a>
		{% endif %}
</div>
{% endblock %}